import { generateId } from './Utilities/GenerateID';

export const HEADER_TITLES = [
  'Company',
  'Stage',
  'Interview Date',
  'Postion',
  'Location',
  'Posting URL',
  'Point of Contact',
  'Contact Info',
  'Date Applied',
];

const jobInput = [
  {
    id: generateId(),
    company: 'Google',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.comjohndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Better',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'DoorDash',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Robinhood',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Samsara',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Brooklinen',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Attentive',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Loom',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Varkada',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Nuvia',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Durchie',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Brex',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Capsule',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Modern Health',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Curative',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Modern Health',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Curative',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Nuro',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Quibi',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Deliver',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Drift',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Instabase',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Upkey',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'UnQork',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Tula Skincare',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Masterclass',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Trello',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Slack',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Verily',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Google',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.comjohndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Better',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'DoorDash',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Robinhood',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Samsara',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Brooklinen',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Attentive',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Loom',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Varkada',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Nuvia',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Durchie',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Brex',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Capsule',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Modern Health',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Curative',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Modern Health',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Curative',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Nuro',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Quibi',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Deliver',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Drift',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Instabase',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Upkey',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'UnQork',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Tula Skincare',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Masterclass',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Trello',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Slack',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Verily',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Google',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.comjohndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Better',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'DoorDash',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Robinhood',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Samsara',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Brooklinen',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Attentive',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Loom',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Varkada',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Nuvia',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Durchie',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Brex',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Capsule',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Modern Health',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Curative',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Modern Health',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Curative',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Nuro',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Quibi',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Deliver',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Drift',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Instabase',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Upkey',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'UnQork',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Tula Skincare',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Masterclass',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Trello',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Slack',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Verily',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Google',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.comjohndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Better',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'DoorDash',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Robinhood',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Samsara',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Brooklinen',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Attentive',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Loom',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Varkada',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Nuvia',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Durchie',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Brex',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Capsule',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Modern Health',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Curative',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Modern Health',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Curative',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Nuro',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Quibi',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Deliver',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Drift',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Instabase',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Upkey',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'UnQork',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Tula Skincare',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Masterclass',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Trello',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Slack',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Verily',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Google',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.comjohndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Better',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'DoorDash',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Robinhood',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Samsara',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Brooklinen',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Attentive',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Loom',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Varkada',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Nuvia',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Durchie',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Brex',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Capsule',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Modern Health',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Curative',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Modern Health',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Curative',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Nuro',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Quibi',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Deliver',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Drift',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Instabase',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Upkey',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'UnQork',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Tula Skincare',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Masterclass',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Trello',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Slack',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Verily',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
];

export default jobInput;
