import { generateId } from './Utilities/GenerateID';
const jobInput = [
  {
    id: generateId(),
    company: 'Google',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.comjohndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Google',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Google',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Google',
    stage: 'Applied',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Mountain View, CA',
    postingURL: 'www.google.com',
    notes: '',
    dateApplied: '01/01/2019',
    pointOfContact: 'John Doe',
    contactInfo: 'johndoe@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
  {
    id: generateId(),
    company: 'Facebook',
    stage: 'Rejected',
    interviewDate: '01/013/2022',
    position: 'Software Engineer',
    location: 'Boston, MA',
    postingURL: 'www.facebook.com',
    notes: '',
    dateApplied: '01/013/2022',
    pointOfContact: 'Adam Smith',
    contactInfo: 'adamsmith@gmail.com',
  },
];

export default jobInput;
